module.exports = {
  'rules' : {
    'color-hex-case': 'lower',
    'color-named': 'never',
    'color-no-invalid-hex': true,
    'font-family-name-quotes': 'always-where-recommended',
    'font-family-no-duplicate-names': true,
    'font-weight-notation': 'named-where-possible',
    'function-calc-no-unspaced-operator': true,
    'function-comma-newline-after': 'never-multi-line',
    'function-comma-space-after': 'always',
    'function-comma-space-before': 'never',
    'number-leading-zero': 'never',
    'number-max-precision': 2,
    'number-no-trailing-zeros': true,
    'string-no-newline': true,
    'string-quotes': 'double',
    'length-zero-no-unit': true,
    'unit-case': 'lower',
    'value-keyword-case': 'lower',
    'value-list-comma-newline-after': 'always-multi-line',
    'value-list-comma-space-after': 'always',
    'value-list-comma-space-before': 'never',
    'shorthand-property-no-redundant-values': true,
    'property-case': 'lower',
    'declaration-bang-space-before': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-colon-space-after': 'always',
    'declaration-no-important': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-block-semicolon-space-after': 'always-single-line',
    'declaration-block-trailing-semicolon': 'always',
    'block-no-empty': true,
    'block-closing-brace-newline-before': 'always',
    'selector-list-comma-space-after': 'always',
    'selector-list-comma-space-before': 'never',
    'rule-empty-line-before': 'always-multi-line',
    'comment-no-empty': true,
    'no-extra-semicolons': true,
    'indentation': 2,
    // 'stylelint-value-border-zero': {
    //   'convention': '0' // Or "none"
    // }
  }
};
